# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  verbs-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: verbs-mysql
    volumes:
      - verbs-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verbs
      - MYSQL_DATABASE=verbs
      - MYSQL_USER=verbs
      - MYSQL_PASSWORD=verbs
